[build]
  command = "npm run build"
  publish = "build"


[template.environment]
  REACT_APP_ENDPOINT = "Your Appwrite Server Endpoint"
  REACT_APP_PROJECT = "Your Appwrite project ID"
  REACT_APP_COLLECTION_ID = "Your Collection ID"